package main

var Templates = map[string]*Template{
	"手动模式": nil,
	"简单共晶相图": {
		Params: []ParamDef{
			{Label: "熔点 A (°C)", Key: "melt_a", Default: 1000.0},
			{Label: "熔点 B (°C)", Key: "melt_b", Default: 1200.0},
			{Label: "共晶温度 (°C)", Key: "e_temp", Default: 600.0},
			{Label: "共晶成分 (B%)", Key: "e_comp", Default: 40.0},
			{Label: "最大固溶度 A (B%)", Key: "sol_a", Default: 5.0},
			{Label: "最大固溶度 B (B%)", Key: "sol_b", Default: 95.0},
		},
		Topology: Topology{
			Points: []PointDef{
				{Label: "A", Comp: "0", Temp: "melt_a"},
				{Label: "B", Comp: "100", Temp: "melt_b"},
				{Label: "E", Comp: "e_comp", Temp: "e_temp"},
				{Label: "S1", Comp: "sol_a", Temp: "e_temp"},
				{Label: "S2", Comp: "sol_b", Temp: "e_temp"},
				{Label: "S10", Comp: "0", Temp: "0"},
				{Label: "S20", Comp: "100", Temp: "0"},
			},
			Lines: []LineDef{
				{Start: "A", End: "E", Type: "liquidus", Curve: 0},
				{Start: "B", End: "E", Type: "liquidus", Curve: 0},
				{Start: "A", End: "S1", Type: "solidus", Curve: 0},
				{Start: "B", End: "S2", Type: "solidus", Curve: 0},
				{Start: "S1", End: "E", Type: "eutectic", Curve: 0},
				{Start: "E", End: "S2", Type: "eutectic", Curve: 0},
				{Start: "S1", End: "S10", Type: "solvus", Curve: 0},
				{Start: "S2", End: "S20", Type: "solvus", Curve: 0},
			},
			Regions: []RegionDef{
				{Label: "L", Points: []string{"A", "E", "B", "T_RIGHT", "T_LEFT"}},
				{Label: "L+α", Points: []string{"A", "E", "S1"}},
				{Label: "L+β", Points: []string{"B", "E", "S2"}},
				{Label: "α", Points: []string{"A", "S1", "S10", "B_LEFT"}},
				{Label: "β", Points: []string{"B", "S2", "S20", "B_RIGHT"}},
				{Label: "α+β", Points: []string{"S1", "E", "S2", "S20", "S10"}},
			},
		},
	},
	"包晶相图_Pt_Ag": {
		Params: []ParamDef{
			{Label: "熔点 Pt (°C)", Key: "melt_pt", Default: 1769.0},
			{Label: "熔点 Ag (°C)", Key: "melt_ag", Default: 961.0},
			{Label: "包晶温度 (°C)", Key: "p_temp", Default: 1186.0},
			{Label: "包晶 α 固相(D) (Ag%)", Key: "p_a_comp", Default: 10.5},
			{Label: "包晶 β 固相(P) (Ag%)", Key: "p_b_comp", Default: 42.5},
			{Label: "包晶液相(C) (Ag%)", Key: "p_l_comp", Default: 66.3},
			{Label: "室温 α 固溶度 (Ag%)", Key: "sol_a_rt", Default: 2.0},
			{Label: "室温 β 固溶度 (Ag%)", Key: "sol_b_rt", Default: 90.0},
		},
		Topology: Topology{
			Points: []PointDef{
				{Label: "A", Comp: "0", Temp: "melt_pt"},
				{Label: "B", Comp: "100", Temp: "melt_ag"},
				{Label: "D", Comp: "p_a_comp", Temp: "p_temp"},
				{Label: "P", Comp: "p_b_comp", Temp: "p_temp"},
				{Label: "C", Comp: "p_l_comp", Temp: "p_temp"},
				{Label: "S_a0", Comp: "sol_a_rt", Temp: "0"},
				{Label: "S_b0", Comp: "sol_b_rt", Temp: "0"},
			},
			Lines: []LineDef{
				{Start: "A", End: "C", Type: "liquidus", Curve: 0},
				{Start: "B", End: "C", Type: "liquidus", Curve: 0},
				{Start: "A", End: "D", Type: "solidus", Curve: 0},
				{Start: "B", End: "P", Type: "solidus", Curve: 0},
				{Start: "D", End: "P", Type: "peritectic", Curve: 0},
				{Start: "P", End: "C", Type: "peritectic", Curve: 0},
				{Start: "D", End: "S_a0", Type: "solvus", Curve: 0},
				{Start: "P", End: "S_b0", Type: "solvus", Curve: 0},
			},
			Regions: []RegionDef{
				{Label: "L", Points: []string{"A", "C", "B", "T_RIGHT", "T_LEFT"}},
				{Label: "α", Points: []string{"A", "D", "S_a0", "B_LEFT"}},
				{Label: "β", Points: []string{"B", "P", "S_b0", "B_RIGHT"}},
				{Label: "α+L", Points: []string{"A", "D", "C"}},
				{Label: "β+L", Points: []string{"B", "P", "C"}},
				{Label: "α+β", Points: []string{"D", "P", "S_b0", "S_a0"}},
			},
		},
	},
	"溶混间隙相图_Cu_Pb_NIST": {
		Params: []ParamDef{
			{Label: "熔点 Cu (°C)", Key: "melt_cu", Default: 1084.5},
			{Label: "熔点 Pb (°C)", Key: "melt_pb", Default: 327.5},
			{Label: "偏晶温度 (°C)", Key: "mono_temp", Default: 956.2},
			{Label: "偏晶 L1 成分 (Pb%)", Key: "mono_l1", Default: 47.75},
			{Label: "偏晶 L2 成分 (Pb%)", Key: "mono_l2", Default: 85.9},
			{Label: "偏晶固相成分 (Pb%)", Key: "mono_s", Default: 0.01},
			{Label: "间隙最高温度 (°C)", Key: "gap_temp", Default: 1000.0},
			{Label: "间隙最高成分 (Pb%)", Key: "gap_comp", Default: 66.8},
			{Label: "共晶温度 (°C)", Key: "e_temp", Default: 326.3},
			{Label: "共晶成分 (Pb%)", Key: "e_comp", Default: 99.94},
		},
		Topology: Topology{
			Points: []PointDef{
				{Label: "A", Comp: "0", Temp: "melt_cu"},
				{Label: "B", Comp: "100", Temp: "melt_pb"},
				{Label: "M_S", Comp: "mono_s", Temp: "mono_temp"},
				{Label: "M_L1", Comp: "mono_l1", Temp: "mono_temp"},
				{Label: "M_L2", Comp: "mono_l2", Temp: "mono_temp"},
				{Label: "Dome", Comp: "gap_comp", Temp: "gap_temp"},
				{Label: "E_L", Comp: "e_comp", Temp: "e_temp"},
				{Label: "S_Cu0", Comp: "0", Temp: "0"},
				{Label: "S_Pb0", Comp: "100", Temp: "0"},
			},
			Lines: []LineDef{
				{Start: "A", End: "M_L1", Type: "liquidus", Curve: 0},
				{Start: "M_L2", End: "E_L", Type: "liquidus", Curve: 0},
				{Start: "E_L", End: "B", Type: "liquidus", Curve: 0},
				{Start: "A", End: "M_S", Type: "solidus", Curve: 0},
				{Start: "M_L1", End: "Dome", Type: "other", Curve: 0},
				{Start: "Dome", End: "M_L2", Type: "other", Curve: 0},
				{Start: "M_S", End: "M_L1", Type: "peritectic", Curve: 0},
				{Start: "M_L1", End: "M_L2", Type: "peritectic", Curve: 0},
				{Start: "M_S", End: "S_Cu0", Type: "solvus", Curve: 0},
				{Start: "S_Cu0", End: "E_L", Type: "eutectic", Curve: 0},
				{Start: "E_L", End: "S_Pb0", Type: "eutectic", Curve: 0},
			},
			Regions: []RegionDef{
				{Label: "L", Points: []string{"A", "M_L1", "Dome", "M_L2", "E_L", "B", "T_RIGHT", "T_LEFT"}},
				{Label: "L1+L2", Points: []string{"M_L1", "Dome", "M_L2"}},
				{Label: "Cu+L1", Points: []string{"A", "M_S", "M_L1"}},
				{Label: "Cu+L2", Points: []string{"M_S", "M_L1", "M_L2", "E_L", "S_Cu0"}},
				{Label: "Pb+L2", Points: []string{"E_L", "B", "S_Pb0"}},
				{Label: "Cu+Pb", Points: []string{"S_Cu0", "E_L", "S_Pb0", "B_RIGHT", "B_LEFT"}},
			},
		},
	},
	"铁碳相图_Fe_Fe3C": {
		Params: []ParamDef{
			{Label: "纯铁熔点 (°C)", Key: "melt_fe", Default: 1538.0},
			{Label: "Fe3C 假想熔点 (°C)", Key: "melt_cem", Default: 1227.0},
			{Label: "包晶温度 (°C)", Key: "p_temp", Default: 1495.0},
			{Label: "包晶 H 点 (C%)", Key: "p_h", Default: 0.09},
			{Label: "包晶 J 点 (C%)", Key: "p_j", Default: 0.17},
			{Label: "包晶 B 点 (C%)", Key: "p_b", Default: 0.53},
			{Label: "共晶温度 (°C)", Key: "e_temp", Default: 1147.0},
			{Label: "共晶 C 点 (C%)", Key: "e_c", Default: 4.3},
			{Label: "最大 γ 固溶 E 点 (C%)", Key: "e_e", Default: 2.11},
			{Label: "共析温度 (°C)", Key: "eut_temp", Default: 727.0},
			{Label: "共析 S 点 (C%)", Key: "eut_s", Default: 0.77},
			{Label: "最大 α 固溶 P 点 (C%)", Key: "eut_p", Default: 0.0218},
			{Label: "渗碳体成分 (C%)", Key: "comp_cem", Default: 6.69},
		},
		Topology: Topology{
			Points: []PointDef{
				{Label: "A", Comp: "0", Temp: "melt_fe"},
				{Label: "N", Comp: "0", Temp: "1394"},
				{Label: "G", Comp: "0", Temp: "912"},
				{Label: "H", Comp: "p_h", Temp: "p_temp"},
				{Label: "J", Comp: "p_j", Temp: "p_temp"},
				{Label: "B", Comp: "p_b", Temp: "p_temp"},
				{Label: "E", Comp: "e_e", Temp: "e_temp"},
				{Label: "C", Comp: "e_c", Temp: "e_temp"},
				{Label: "F", Comp: "comp_cem", Temp: "e_temp"},
				{Label: "P", Comp: "eut_p", Temp: "eut_temp"},
				{Label: "S", Comp: "eut_s", Temp: "eut_temp"},
				{Label: "K", Comp: "comp_cem", Temp: "eut_temp"},
				{Label: "Q", Comp: "0.0008", Temp: "0"},
				{Label: "Cem0", Comp: "comp_cem", Temp: "0"},
				{Label: "D", Comp: "comp_cem", Temp: "melt_cem"},
				{Label: "Fe_RT", Comp: "0", Temp: "0"},
			},
			Lines: []LineDef{
				{Start: "A", End: "B", Type: "liquidus", Curve: 0},
				{Start: "B", End: "C", Type: "liquidus", Curve: 0},
				{Start: "C", End: "D", Type: "liquidus", Curve: 0},
				{Start: "A", End: "H", Type: "solidus", Curve: 0},
				{Start: "J", End: "E", Type: "solidus", Curve: 0},
				{Start: "H", End: "J", Type: "peritectic", Curve: 0},
				{Start: "J", End: "B", Type: "peritectic", Curve: 0},
				{Start: "N", End: "H", Type: "solvus", Curve: 0},
				{Start: "N", End: "J", Type: "solvus", Curve: 0},
				{Start: "E", End: "C", Type: "eutectic", Curve: 0},
				{Start: "C", End: "F", Type: "eutectic", Curve: 0},
				{Start: "G", End: "S", Type: "solvus", Curve: 0},
				{Start: "E", End: "S", Type: "solvus", Curve: 0},
				{Start: "G", End: "P", Type: "solvus", Curve: 0},
				{Start: "P", End: "S", Type: "eutectoid", Curve: 0},
				{Start: "S", End: "K", Type: "eutectoid", Curve: 0},
				{Start: "P", End: "Q", Type: "solvus", Curve: 0},
				{Start: "F", End: "K", Type: "solidus", Curve: 0},
				{Start: "K", End: "Cem0", Type: "solidus", Curve: 0},
				{Start: "F", End: "D", Type: "solidus", Curve: 0},
			},
			Regions: []RegionDef{
				{Label: "L", Points: []string{"A", "B", "C", "D", "T_RIGHT", "T_LEFT"}},
				{Label: "δ+L", Points: []string{"A", "B", "J", "H"}},
				{Label: "δ", Points: []string{"A", "H", "N"}},
				{Label: "δ+γ", Points: []string{"N", "H", "J"}},
				{Label: "γ+L", Points: []string{"J", "B", "C", "E"}},
				{Label: "L+Fe3C", Points: []string{"C", "D", "F"}},
				{Label: "γ", Points: []string{"N", "J", "E", "S", "G"}},
				{Label: "γ+Fe3C", Points: []string{"E", "C", "F", "K", "S"}},
				{Label: "α+γ", Points: []string{"G", "S", "P"}},
				{Label: "α", Points: []string{"G", "P", "Q", "Fe_RT"}},
				{Label: "α+Fe3C", Points: []string{"P", "S", "K", "Cem0", "Q"}},
			},
		},
	},
	"匀晶(固溶体)相图": {
		Params: []ParamDef{
			{Label: "熔点 A (°C)", Key: "melt_a", Default: 1000.0},
			{Label: "熔点 B (°C)", Key: "melt_b", Default: 1300.0},
		},
		Topology: Topology{
			Points: []PointDef{
				{Label: "A", Comp: "0", Temp: "melt_a"},
				{Label: "B", Comp: "100", Temp: "melt_b"},
			},
			Lines: []LineDef{
				{Start: "A", End: "B", Type: "liquidus", Curve: 0},
				{Start: "A", End: "B", Type: "solidus", Curve: 0},
			},
			Regions: []RegionDef{
				{Label: "L", Points: []string{"A", "B", "T_RIGHT", "T_LEFT"}},
				{Label: "α", Points: []string{"A", "B", "B_RIGHT", "B_LEFT"}},
			},
		},
	},
}
