package main

var TernaryTemplates = map[string]*TernaryTemplate{
	"简单共晶": {
		Points: []TernaryPoint{
			{Label: "A", A: 100, B: 0, C: 0, Temp: 1000},
			{Label: "B", A: 0, B: 100, C: 0, Temp: 1050},
			{Label: "C", A: 0, B: 0, C: 100, Temp: 1100},
			{Label: "D", A: 45, B: 55, C: 0, Temp: 900},
			{Label: "E", A: 0, B: 45, C: 55, Temp: 850},
			{Label: "F", A: 45, B: 0, C: 55, Temp: 800},
			{Label: "G", A: 32, B: 37, C: 31, Temp: 700},
		},
		Lines: []TernaryLine{
			{Start: "A", End: "F", CurveX: 0, CurveY: 0, CurveZ: 25},
			{Start: "F", End: "C", CurveX: 0, CurveY: 0, CurveZ: 30},
			{Start: "C", End: "E", CurveX: 0, CurveY: 0, CurveZ: 30},
			{Start: "B", End: "E", CurveX: 0, CurveY: 0, CurveZ: 30},
			{Start: "A", End: "D", CurveX: 0, CurveY: 0, CurveZ: 30},
			{Start: "B", End: "D", CurveX: 0, CurveY: 0, CurveZ: 30},
			{Start: "D", End: "G", CurveX: 0, CurveY: 10, CurveZ: 10},
			{Start: "E", End: "G", CurveX: 0, CurveY: 10, CurveZ: -10},
			{Start: "F", End: "G", CurveX: 10, CurveY: 0, CurveZ: 10},
		},
		Surfaces: []TernarySurface{
			{LineLabels: []string{"AD", "DG", "GF", "FA"}},
			{LineLabels: []string{"BD", "DG", "GE", "EB"}},
			{LineLabels: []string{"CF", "FG", "GE", "EC"}},
		},
	},
	"简单三元共晶": {
		Points: []TernaryPoint{
			{Label: "A", A: 100, B: 0, C: 0, Temp: 1000},
			{Label: "B", A: 0, B: 100, C: 0, Temp: 950},
			{Label: "C", A: 45, B: 55, C: 0, Temp: 800},
			{Label: "F", A: 0, B: 0, C: 100, Temp: 1050},
			{Label: "G", A: 45, B: 0, C: 55, Temp: 850},
			{Label: "I", A: 32, B: 37, C: 31, Temp: 600},
			{Label: "J", A: 100, B: 0, C: 0, Temp: 600},
			{Label: "K", A: 0, B: 100, C: 0, Temp: 600},
			{Label: "L", A: 0, B: 0, C: 100, Temp: 600},
			{Label: "M", A: 0, B: 45, C: 55, Temp: 750},
			{Label: "D", A: 100, B: 0, C: 0, Temp: 850},
			{Label: "E", A: 0, B: 0, C: 100, Temp: 850},
			{Label: "H", A: 100, B: 0, C: 0, Temp: 800},
			{Label: "N", A: 0, B: 100, C: 0, Temp: 800},
			{Label: "O", A: 0, B: 100, C: 0, Temp: 750},
			{Label: "P", A: 0, B: 0, C: 100, Temp: 750},
		},
		Lines: []TernaryLine{
			{Start: "A", End: "C", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "A", End: "G", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "C", End: "I", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "G", End: "I", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "I", End: "J", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "J", End: "L", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "I", End: "L", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "A", End: "J", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "F", End: "G", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "B", End: "C", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "B", End: "M", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "F", End: "M", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "K", End: "L", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "K", End: "J", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "K", End: "I", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "E", End: "L", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "E", End: "G", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "D", End: "G", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "D", End: "J", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "H", End: "C", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "J", End: "H", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "C", End: "N", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "M", End: "O", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "M", End: "P", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "I", End: "M", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "K", End: "O", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "K", End: "N", CurveX: 0, CurveY: 0, CurveZ: 0},
		},
		Surfaces: []TernarySurface{
			{LineLabels: []string{"AG", "GI", "IC", "CA"}},
			{LineLabels: []string{"BC", "CI", "IM", "MB"}},
			{LineLabels: []string{"FG", "GI", "IM", "MF"}},
			{LineLabels: []string{"DG", "GI", "IJ", "JD"}},
			{LineLabels: []string{"IJ", "JL", "LI"}},
		},
	},
	"三元共晶-完整版": {
		Points: []TernaryPoint{
			{Label: "A", A: 100, B: 0, C: 0, Temp: 1000},
			{Label: "B", A: 0, B: 100, C: 0, Temp: 950},
			{Label: "C", A: 45, B: 55, C: 0, Temp: 800},
			{Label: "F", A: 0, B: 0, C: 100, Temp: 1050},
			{Label: "G", A: 45, B: 0, C: 55, Temp: 850},
			{Label: "I", A: 32, B: 37, C: 31, Temp: 600},
			{Label: "J", A: 100, B: 0, C: 0, Temp: 600},
			{Label: "K", A: 0, B: 100, C: 0, Temp: 600},
			{Label: "L", A: 0, B: 0, C: 100, Temp: 600},
			{Label: "M", A: 0, B: 45, C: 55, Temp: 750},
			{Label: "D", A: 100, B: 0, C: 0, Temp: 850},
			{Label: "E", A: 0, B: 0, C: 100, Temp: 850},
			{Label: "H", A: 100, B: 0, C: 0, Temp: 800},
			{Label: "N", A: 0, B: 100, C: 0, Temp: 800},
			{Label: "O", A: 0, B: 100, C: 0, Temp: 750},
			{Label: "P", A: 0, B: 0, C: 100, Temp: 750},
		},
		Lines: []TernaryLine{
			{Start: "A", End: "C", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "A", End: "G", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "C", End: "I", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "G", End: "I", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "I", End: "J", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "J", End: "L", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "I", End: "L", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "A", End: "J", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "F", End: "G", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "B", End: "C", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "B", End: "M", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "F", End: "M", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "K", End: "L", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "K", End: "J", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "K", End: "I", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "E", End: "L", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "E", End: "G", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "D", End: "G", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "D", End: "J", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "H", End: "C", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "J", End: "H", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "C", End: "N", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "M", End: "O", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "M", End: "P", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "I", End: "M", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "K", End: "O", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "K", End: "N", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "L", End: "P", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "M", End: "N", CurveX: 0, CurveY: 0, CurveZ: 0},
		},
		Surfaces: []TernarySurface{
			{LineLabels: []string{"JD", "DG", "GI", "IJ"}},
			{LineLabels: []string{"PM", "MI", "IL", "LP"}},
			{LineLabels: []string{"NK", "KI", "IC", "CN"}},
			{LineLabels: []string{"LE", "EG", "GI", "IL"}},
			{LineLabels: []string{"JH", "HC", "CI", "IJ"}},
			{LineLabels: []string{"NK", "KI", "IM", "MN"}},
			{LineLabels: []string{"BM", "MI", "IC", "CB"}},
			{LineLabels: []string{"AC", "CI", "IG", "GA"}},
			{LineLabels: []string{"FG", "GI", "IM", "MF"}},
			{LineLabels: []string{"IL", "LK", "KI"}},
			{LineLabels: []string{"IK", "KJ", "JI"}},
			{LineLabels: []string{"IL", "LJ", "JI"}},
		},
	},
	"复杂三元共晶": {
		Points: []TernaryPoint{
			{Label: "A", A: 100, B: 0, C: 0, Temp: 1000},
			{Label: "B", A: 0, B: 100, C: 0, Temp: 1050},
			{Label: "C", A: 0, B: 0, C: 100, Temp: 1100},
			{Label: "D", A: 45, B: 55, C: 0, Temp: 700},
			{Label: "E", A: 55, B: 0, C: 45, Temp: 670},
			{Label: "F", A: 0, B: 50, C: 50, Temp: 640},
			{Label: "G", A: 20, B: 80, C: 0, Temp: 700},
			{Label: "H", A: 80, B: 20, C: 0, Temp: 700},
			{Label: "I", A: 90, B: 10, C: 0, Temp: 0},
			{Label: "J", A: 10, B: 90, C: 0, Temp: 0},
			{Label: "K", A: 20, B: 0, C: 80, Temp: 670},
			{Label: "L", A: 80, B: 0, C: 20, Temp: 670},
			{Label: "M", A: 10, B: 0, C: 90, Temp: 0},
			{Label: "N", A: 90, B: 0, C: 10, Temp: 0},
			{Label: "O", A: 0, B: 20, C: 80, Temp: 640},
			{Label: "P", A: 0, B: 80, C: 20, Temp: 640},
			{Label: "Q", A: 0, B: 10, C: 90, Temp: 0},
			{Label: "R", A: 0, B: 90, C: 10, Temp: 0},
			{Label: "S", A: 6, B: 6, C: 80, Temp: 0},
			{Label: "T", A: 88, B: 6, C: 6, Temp: 0},
			{Label: "U", A: 6, B: 88, C: 6, Temp: 0},
			{Label: "V", A: 33, B: 33, C: 32, Temp: 400},
			{Label: "W", A: 15, B: 15, C: 70, Temp: 400},
			{Label: "X", A: 70, B: 15, C: 15, Temp: 400},
			{Label: "Y", A: 15, B: 70, C: 15, Temp: 400},
		},
		Lines: []TernaryLine{
			{Start: "A", End: "L", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "A", End: "E", CurveX: 0, CurveY: 0, CurveZ: 150},
			{Start: "C", End: "E", CurveX: 0, CurveY: 0, CurveZ: 150},
			{Start: "C", End: "K", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "L", End: "K", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "K", End: "M", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "L", End: "N", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "A", End: "H", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "A", End: "D", CurveX: 0, CurveY: 0, CurveZ: 150},
			{Start: "B", End: "D", CurveX: 0, CurveY: 0, CurveZ: 150},
			{Start: "B", End: "G", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "G", End: "H", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "H", End: "I", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "J", End: "G", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "B", End: "P", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "B", End: "F", CurveX: 0, CurveY: 0, CurveZ: 150},
			{Start: "C", End: "F", CurveX: 0, CurveY: 0, CurveZ: 150},
			{Start: "C", End: "O", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "O", End: "P", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "P", End: "R", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "O", End: "Q", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "K", End: "W", CurveX: 0, CurveY: 0, CurveZ: -80},
			{Start: "O", End: "W", CurveX: 0, CurveY: 0, CurveZ: -80},
			{Start: "W", End: "S", CurveX: 0, CurveY: 0, CurveZ: 60},
			{Start: "X", End: "H", CurveX: 0, CurveY: 0, CurveZ: -80},
			{Start: "X", End: "L", CurveX: 0, CurveY: 0, CurveZ: -80},
			{Start: "T", End: "X", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "G", End: "Y", CurveX: 0, CurveY: 0, CurveZ: -80},
			{Start: "P", End: "Y", CurveX: 0, CurveY: 0, CurveZ: -80},
			{Start: "Y", End: "U", CurveX: 0, CurveY: 0, CurveZ: 80},
			{Start: "I", End: "T", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "T", End: "N", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "M", End: "S", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "Q", End: "S", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "J", End: "U", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "R", End: "U", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "T", End: "U", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "T", End: "S", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "U", End: "S", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "Y", End: "X", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "Y", End: "W", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "X", End: "W", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "F", End: "V", CurveX: -4, CurveY: 0, CurveZ: 50},
			{Start: "D", End: "V", CurveX: 0, CurveY: 5, CurveZ: 50},
			{Start: "E", End: "V", CurveX: 0, CurveY: 3, CurveZ: 50},
			{Start: "W", End: "V", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "V", End: "X", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "V", End: "Y", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "K", End: "E", CurveX: 0, CurveY: 0, CurveZ: 0},
			{Start: "E", End: "L", CurveX: 0, CurveY: 0, CurveZ: 0},
		},
		Surfaces: []TernarySurface{
			{LineLabels: []string{"VE", "EK", "KW", "WV"}},
			{LineLabels: []string{"EL", "LX", "XV", "VE"}},
			{LineLabels: []string{"LK", "KW", "WX", "XL"}},
			{LineLabels: []string{"VX", "XW", "WV"}},
		},
	},
}
